### ISSUE TITLE
Ui bugs

### ISSUE THREAD

**Issue by bozd4g** [Trendyol/four-key#4]
Hello @aslihanozfidan ,

I see a few bugs occurring during your development. Can u fix these?

These bugs are as follows;

![image](https://user-images.githubusercontent.com/27498814/89756406-0ee0ba80-daeb-11ea-95b4-a39a0e699a48.png)

**Comment by bozd4g** [comment]
Also "Average" button does not working @aslihanozfidan

**Comment by burakolgun** [comment]
As mentioned at the description of pull request https://github.com/Trendyol/four-key/pull/3  average button has been disabled for preventing misunderstandings. We are going to enable it after this calculation fix -> https://github.com/Trendyol/four-key/projects/2#card-43267128 @bozd4g

**Comment by aslihanozfidan** [comment]
Hi @bozd4g,

Dates and names were changed as dynamic.
Thank you for your attention.
